version: '3.8'

services:
  backend:
    build:
      context: ./backend/backend-ai
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend/backend-ai:/app
    depends_on:
      - ai-service
    environment:
      - AI_SERVICE_URL=http://ai-service:11434

  ai-service:
    build:
      context: ./backend/backend-ai/ai-service
      dockerfile: Dockerfile  # Capitalized if your file is actually named "Dockerfile"
    ports:
      - "11434:11434"
    volumes:
      - ./backend/backend-ai/ai-service:/app
    command: uvicorn main:app --host 0.0.0.0 --port 11434

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    environment:
      - REACT_APP_API_URL=http://backend:8000
    depends_on:
      - backend
