version: '3.8'

services:
  backend:
    build:
      context: ./backend/backend-ai  # Adjusted to real backend path
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend/backend-ai:/app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    environment:
      - REACT_APP_API_URL=http://backend:8000
    depends_on:
      - backend
