version: '3.9'

services:
  backend:
    build:
      context: ./backend/backend-ai
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend/backend-ai:/app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    command: npx serve -s dist  
    environment:
      - REACT_APP_API_BASE_URL=http://backend:8000
    depends_on:
      - backend
