#cloud-config
package_update: true
package_upgrade: true
packages:
  - curl

runcmd:
  - curl -fsSL https://ollama.com/install.sh | sh
  - systemctl enable ollama
  - systemctl start ollama
  - su - alens -c "ollama run llava"
