services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

  backend:
    build:
      context: .  # allow access to full monorepo (so COPY libs/lib2 works)
      dockerfile: backend/backend-ai/Dockerfile
    env_file:
      - .env
    environment:
      - AI_SERVICE_URL=http://ai-service:8000
    ports:
      - "8000:8000"
    depends_on:
      ai-service:
        condition: service_healthy
    entrypoint: /entrypoint.sh
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 10s
      timeout: 5s
      retries: 3

  ai-service:
    build:
      context: ./backend/backend-ai/ai-service
      dockerfile: Dockerfile
    ports:
      - "8001:8000"  # backend talks to 8000 inside container, 8001 is host-visible
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 10s
      timeout: 5s
      retries: 3
