version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - ai-service

  ai-service:
    build:
      context: .
      dockerfile: backend-ai/ai-service/Dockerfile
    ports:
      - "11434:11434"
    volumes:
      - ./backend-ai/ai-service:/app
    command: python main.py

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    environment:
      - VITE_API_URL=http://backend:8000
    depends_on:
      - backend
