version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend/backend-ai
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - ai-service
    entrypoint: /entrypoint.sh

  ai-service:
    build:
      context: ./backend/backend-ai/ai-service
      dockerfile: Dockerfile
    ports:
      - "11434:11434"
