version: '3.9'

services:
  ai-service:
    build:
      context: ./backend/backend-ai/ai-service
      dockerfile: Dockerfile
    container_name: deckbot-ai-service
    ports:
      - "${AI_PORT:-8000}:8000"
    volumes:
      - ./backend/backend-ai/ai-service:/app
    env_file:
      - .env
    restart: unless-stopped

  backend:
    build:
      context: ./backend/backend-ai
      dockerfile: Dockerfile
    container_name: deckbot-backend
    ports:
      - "${PORT:-11434}:11434"
    volumes:
      - ./backend/backend-ai:/app
    env_file:
      - .env
    depends_on:
      - ai-service
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: deckbot-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    env_file:
      - .env
    depends_on:
      - backend
    restart: unless-stopped
