version: "3.9"
services:
  backend:
    build: ./backend/backend-ai
    ports:
      - "8000:8000"
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      API_KEY: ${API_KEY:-revamp123secure}
      OPENAI_API_KEY: ${OPENAI_API_KEY:-changeme}
    depends_on:
      - backend

