services:
  - type: web
    name: deckchatbot-frontend
    env: docker
    plan: free
    rootDir: .
    dockerfilePath: ./apps/frontend/Dockerfile
    envVars:
      - key: REACT_APP_API_BASE_URL
        value: https://deckchatbot-backend.onrender.com

  - type: web
    name: deckchatbot-backend
    env: docker
    plan: free
    rootDir: .
    dockerfilePath: ./apps/backend/Dockerfile
    envVars:
      - key: AI_SERVICE_URL
        value: https://deckchatbot-ai-service.onrender.com

  - type: web
    name: deckchatbot-ai-service
    env: docker
    plan: free
    rootDir: .
    dockerfilePath: ./apps/ai-service/Dockerfile
