services:
  - type: web
    name: deckchatbot-frontend
    env: docker
    plan: free
    rootDir: .
    dockerfilePath: apps/frontend/Dockerfile
    envVars:
      - key: REACT_APP_API_BASE_URL
        value: https://deckchatbot-backend.onrender.com

  - type: web
    name: deckchatbot-backend
    env: docker
    plan: free
    rootDir: .
    dockerfilePath: apps/backend/Dockerfile
    envVars:
      - key: AI_SERVICE_URL
        value: https://deckchatbot-ai-service.onrender.com
      - key: AI_PROVIDER
        value: ollama

  - type: web
    name: deckchatbot-ai-service
    env: docker
    plan: free
    rootDir: .
    dockerfilePath: apps/ai-service/Dockerfile
    envVars:
      - key: AI_PROVIDER
        value: ollama
      - key: OLLAMA_BASE_URL
        value: http://localhost:11434 # Ollama is now embedded in this service

# Updated configuration for Ollama integration.
