services:
  - type: web
    name: deckbot-frontend
    env: docker
    repo: https://github.com/alentwotime/deckchatbot-monorepo
    dockerContext: ./frontend
    dockerfilePath: ./frontend/Dockerfile
    branch: main
    plan: free
    envVars:
      - key: REACT_APP_API_URL
        value: https://deckchatbot-backend.onrender.com

  - type: web
    name: deckbot-backend
    env: docker
    repo: https://github.com/alentwotime/deckchatbot-monorepo
    dockerContext: ./backend/app2
    dockerfilePath: ./backend/app2/Dockerfile
    branch: main
    plan: free
    envVars:
      - key: PORT
        value: 8000
      - key: AI_SERVICE_URL
        value: http://ai-service:8000/analyze-image

  - type: web
    name: deckbot-ai-service
    env: docker
    repo: https://github.com/alentwotime/deckchatbot-monorepo
    dockerContext: ./backend/backend-ai/ai-service
    dockerfilePath: ./backend/backend-ai/ai-service/Dockerfile
    branch: main
    plan: free
    envVars:
      - key: PORT
        value: 8000
