services:
  - type: web
    name: deckchatbot-backend
    env: docker
    plan: free
    repo: https://github.com/YOUR_USERNAME/deckchatbot-monorepo
    dockerfilePath: backend/backend-ai/Dockerfile
    buildCommand: ""
    startCommand: "/entrypoint.sh"
    envVars:
      - key: AI_SERVICE_URL
        value: http://ai-service:11434

  - type: web
    name: deckchatbot-frontend
    env: docker
    plan: free
    repo: https://github.com/YOUR_USERNAME/deckchatbot-monorepo
    dockerfilePath: frontend/Dockerfile
    buildCommand: ""
    startCommand: ""
