#cloud-config
package_update: true
packages:
  - docker.io
runcmd:
  - ip addr add 5.161.23.197 dev eth0
  - systemctl start docker
  - systemctl enable docker
  - docker pull myrepo/deckchatbot-backend-ai:latest
  - docker run -d --restart always -p 8000:8000 myrepo/deckchatbot-backend-ai:latest
