services:
  frontend:
    build:
      context: ..
      dockerfile: ./apps/frontend/Dockerfile
    ports:
      - "3000:80"
    restart: unless-stopped
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost" ]
      interval: 10s
      timeout: 5s
      retries: 3
    dns:
      - 8.8.8.8
      - 1.1.1.1
    networks:
      - decknet
    # Security and resource optimizations
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /var/cache/nginx:noexec,nosuid,size=100m
      - /var/run:noexec,nosuid,size=100m
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.5'
        reservations:
          memory: 128M
          cpus: '0.25'

  backend:
    build:
      context: ..
      dockerfile: ./apps/backend/Dockerfile
    env_file:
      - ../.env
      - ../.env.docker
    environment:
      - AI_SERVICE_URL=http://ai-service:8000
      - AI_PROVIDER=${AI_PROVIDER:-openai}
      - OPENAI_API_KEY=${OPENAI_API_KEY:-dummy-openai-key}
      - OPENAI_ADMIN_API_KEY=${OPENAI_ADMIN_API_KEY:-dummy-admin-key}
      - OLLAMA_MODEL_NAME=${OLLAMA_MODEL_NAME:-llava-deckbot}
    ports:
      - "8000:8000"
    restart: unless-stopped
    depends_on:
      ai-service:
        condition: service_healthy
    entrypoint: /app/entrypoint.sh
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/health" ]
      interval: 30s
      timeout: 10s
      start_period: 30s
      retries: 5
    dns:
      - 8.8.8.8
      - 1.1.1.1
    networks:
      - decknet
    # Security and resource optimizations
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1.0'
        reservations:
          memory: 512M
          cpus: '0.5'

  ai-service:
    build:
      context: ..
      dockerfile: ./apps/ai-service/Dockerfile
    env_file:
      - ../.env
      - ../.env.docker
    environment:
      - AI_PROVIDER=ocr
      - HF_API_TOKEN=${HF_API_TOKEN:-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}
      - OPENAI_API_KEY=${OPENAI_API_KEY:-dummy-openai-key}
      - OPENAI_ADMIN_API_KEY=${OPENAI_ADMIN_API_KEY:-dummy-admin-key}
      - SESSION_SECRET=${SESSION_SECRET:-docker-dev-session-secret}
      - JWT_SECRET=${JWT_SECRET:-docker-dev-jwt-secret}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY:-docker-dev-encryption-key-32chars}
      - DATABASE_URL=${DATABASE_URL:-sqlite:///./docker.db}
      - AZURE_AI_KEY=${AZURE_AI_KEY:-dummy-azure-ai-key-for-docker-dev}
    ports:
      - "8001:8000"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/health || exit 1"]
      interval: 30s
      timeout: 15s
      retries: 5
      start_period: 60s
    dns:
      - 8.8.8.8
      - 1.1.1.1
    networks:
      - decknet
    # Security and resource optimizations
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.5'
        reservations:
          memory: 1G
          cpus: '0.75'

networks:
  decknet:
    driver: bridge
    # Removed custom subnet configuration that was causing issues
    driver_opts:
      com.docker.network.bridge.name: decknet
      com.docker.network.driver.mtu: 1500
